package main.java.UserInterface.MultipleSimu;

import main.java.UserInterface.ViewReport.ChooseSimuJPanel;

import javax.swing.*;
import java.awt.*;

/**
 * @Author: LiuLou
 * @Description:
 * @Date: Created in 2:38 2020/11/30
 * @Modified By:
 */
public class MultiSimuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MultiSimuJPanel
     */
    private JPanel jplContainer;

    public MultiSimuJPanel(JPanel jplContainer) {
        initComponents();
        this.jplContainer = jplContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        rbtnMaskNo = new javax.swing.JRadioButton();
        jplCanvas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        rbtnTestYes = new javax.swing.JRadioButton();
        btnViewReport = new javax.swing.JButton();
        rbtnTestNo = new javax.swing.JRadioButton();
        txtPopulationDensity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbtnQuarantineYes = new javax.swing.JRadioButton();
        rbtnQuarantineNo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxPathogen1 = new javax.swing.JComboBox<>();
        btnStartSimu = new javax.swing.JButton();
        rbtnMaskYes = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jplCanvas1 = new javax.swing.JPanel();
        lblPathogen1 = new javax.swing.JLabel();
        jblPathogen2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxPathogen2 = new javax.swing.JComboBox<>();

        rbtnMaskNo.setText("no");
        rbtnMaskNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaskNoActionPerformed(evt);
            }
        });

        jplCanvas.setBackground(new java.awt.Color(255, 255, 255));
        jplCanvas.setPreferredSize(new java.awt.Dimension(340, 340));

        javax.swing.GroupLayout jplCanvasLayout = new javax.swing.GroupLayout(jplCanvas);
        jplCanvas.setLayout(jplCanvasLayout);
        jplCanvasLayout.setHorizontalGroup(
                jplCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 340, Short.MAX_VALUE)
        );
        jplCanvasLayout.setVerticalGroup(
                jplCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 340, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel3.setText("Testing and Contact Tracing");

        btnBack.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.setEnabled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        rbtnTestYes.setText("yes");

        btnViewReport.setBackground(new java.awt.Color(255, 153, 51));
        btnViewReport.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        btnViewReport.setText("See All Reports");
        btnViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportActionPerformed(evt);
            }
        });

        rbtnTestNo.setText("no");
        rbtnTestNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTestNoActionPerformed(evt);
            }
        });

        txtPopulationDensity.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel4.setText("Quarantining");

        jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel1.setText("Population Density");

        rbtnQuarantineYes.setText("yes");

        rbtnQuarantineNo.setText("no");
        rbtnQuarantineNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnQuarantineNoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel2.setText("Wearing Masks");

        jLabel5.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel5.setText("Pathogen1 Type");

        cbxPathogen1.setFont(new java.awt.Font("微软雅黑", 2, 12)); // NOI18N
        cbxPathogen1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnStartSimu.setBackground(new java.awt.Color(0, 0, 0));
        btnStartSimu.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        btnStartSimu.setForeground(new java.awt.Color(255, 0, 0));
        btnStartSimu.setText("Start Simulation");

        rbtnMaskYes.setText("yes");

        jLabel6.setFont(new java.awt.Font("微软雅黑", 1, 16)); // NOI18N
        jLabel6.setText("Multiple Pathogens Simulation Comparison");

        jplCanvas1.setBackground(new java.awt.Color(255, 255, 255));
        jplCanvas1.setPreferredSize(new java.awt.Dimension(340, 340));

        javax.swing.GroupLayout jplCanvas1Layout = new javax.swing.GroupLayout(jplCanvas1);
        jplCanvas1.setLayout(jplCanvas1Layout);
        jplCanvas1Layout.setHorizontalGroup(
                jplCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 340, Short.MAX_VALUE)
        );
        jplCanvas1Layout.setVerticalGroup(
                jplCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        lblPathogen1.setFont(new java.awt.Font("微软雅黑", 3, 14)); // NOI18N
        lblPathogen1.setText("Pathogen1");

        jblPathogen2.setFont(new java.awt.Font("微软雅黑", 3, 14)); // NOI18N
        jblPathogen2.setText("Pathogen2");

        jLabel7.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel7.setText("Pathogen2 Type");

        cbxPathogen2.setFont(new java.awt.Font("微软雅黑", 2, 12)); // NOI18N
        cbxPathogen2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jplCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jplCanvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(63, 63, 63))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(175, 175, 175)
                                                .addComponent(lblPathogen1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jblPathogen2)
                                                .addGap(200, 200, 200)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbtnQuarantineYes)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rbtnQuarantineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnViewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(rbtnMaskYes)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(rbtnMaskNo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(rbtnTestYes)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(rbtnTestNo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbxPathogen1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnStartSimu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtPopulationDensity)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbxPathogen2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 10, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnViewReport)
                                        .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jplCanvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jplCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbxPathogen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbxPathogen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtPopulationDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rbtnMaskYes)
                                                        .addComponent(rbtnMaskNo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rbtnQuarantineYes)
                                                        .addComponent(rbtnQuarantineNo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rbtnTestYes)
                                                        .addComponent(rbtnTestNo))))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblPathogen1)
                                                        .addComponent(jblPathogen2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnBack))
                                        .addComponent(btnStartSimu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void rbtnMaskNoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jplContainer.remove(this);
        CardLayout layout = (CardLayout) jplContainer.getLayout();
        layout.previous(jplContainer);
    }

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        ChooseSimuJPanel csjp = new ChooseSimuJPanel(jplContainer);
        CardLayout cardLayout = (CardLayout) jplContainer.getLayout();
        jplContainer.add("ChooseSimuJPanel",csjp);
        cardLayout.next(jplContainer);
    }

    private void rbtnTestNoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void rbtnQuarantineNoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnStartSimu;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JComboBox<String> cbxPathogen1;
    private javax.swing.JComboBox<String> cbxPathogen2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jblPathogen2;
    private javax.swing.JPanel jplCanvas;
    private javax.swing.JPanel jplCanvas1;
    private javax.swing.JLabel lblPathogen1;
    private javax.swing.JRadioButton rbtnMaskNo;
    private javax.swing.JRadioButton rbtnMaskYes;
    private javax.swing.JRadioButton rbtnQuarantineNo;
    private javax.swing.JRadioButton rbtnQuarantineYes;
    private javax.swing.JRadioButton rbtnTestNo;
    private javax.swing.JRadioButton rbtnTestYes;
    private javax.swing.JTextField txtPopulationDensity;
    // End of variables declaration
}
